LOGIN : 
  ARIA :
    LOGIN_URL : 
    CLIENT_SECRET : 
    CLIENT_ID : 
    SCOPE : account
    GRANT_TYPE : password
    REFRESH_GRANT : refresh_token
    SESSION_KEY : 
    USERNAME : 
    PASSWORD : 
    EMAIL : 

FACILITY :
  ID : 

API :
  LOCAL : 
    DATA_DEPOSITION_BASE : 
    ENTITY_BASE : 
  
  BETA : 
    DATA_DEPOSITION_BASE :
    ENTITY_BASE :

ENDPOINTS : 
  CREATE :
    BUCKET : createDataBucket
    RECORD : createDataRecord
    FIELD : createDataField
  GET : 
    BUCKET : bucket
    RECORD : record
    FIELD : field
    VISITS : visit/feed
    PROPOSAL_DATA : proposal_data/find
    PROPOSAL : proposal/

DEV : LOCAL